config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :users do
    resources :reject_profile_messages
  end

  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
  resources :user_profiles
  post 'welcome_student/reg_backlog'
  post 'welcome_student/sel_for_backlog'
  post 'users/approve_user'
  post 'users/set_fail_log'
  post 'users/set_pass_log'
  post 'users/set_fail'
  post 'users/set_pass'
  get 'welcome_student/course_status'
  post 'welcome_student/course_status'
  get 'courses/show_courses_user'
  get 'courses/show_user'
  post 'welcome_student/enroll_courses'
  post 'welcome_student/sel_to_enroll'
  post 'welcome_student/available_courses'
  get 'welcome_student/available_courses'
  get 'departments/show_user'
  get 'course_dept/show_courses_user'
  get 'welcome_student/index'
  post 'course_dept/remove_course'
  post 'course_dept/add_course'
  post 'course_dept/sel_course'
  get 'course_dept/show_courses'
  get 'course_dept/index'
  get 'welcome/index'

  get 'first/index'
  root 'first#index'
  resources :admins
  resources :departments
  resources :courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount ActionCable.server => '/cable'
end

app/controllers/welcome_student_controller.rb
class WelcomeStudentController < ApplicationController
  skip_before_action :authenticate_admin!
  
  @@selected_courses = []
  @@selected_courses_backlog = []

  def index
    if user_signed_in?
      @user = current_user
      @user_id = @user.id
      @user_name = @user.name
      @user_email = @user.email

      if @user.user_profile == nil
        @check = 1
      elsif @user.user_profile && @user.user_profile.approved==false
        @check = 2
      else
        @check = 3
      end

      if @check==3
        @user_passed_courses = CourseUser.where(user_id: @user_id, result: 1)
        @user_curr_courses = CourseUser.where(user_id: @user_id, semester: @user.user_profile.current_semester)
        @user_curr_courses_info = []
        @user_curr_courses.each do |uc|
          @c = Course.find_by(id: uc.course_id)
          @s = "pending"
          if uc.result == 1
            @s = "passed"
          elsif uc.result == 2
            @s = "failed"
          end
          @user_curr_courses_info.append(code:@c.code, title:@c.title, status:@s)
        end
      end
    end
  end

  def set_reject_msg
    
  end

  def available_courses
    @user = User.find(params[:u_id])
    @x = CourseUser.where(user_id: @user.id, semester: @user.user_profile.current_semester, result:0)
    @notice = ""
    if @x.count > 0
      @notice = "You can't register for new semester now. The result of your current semester hasn't been published yet."
    end
  end

  def sel_to_enroll
    @course = Course.find(params[:course_id])
    @@selected_courses.append(@course)
  end

  def enroll_courses
    @user = User.find(params[:u_id])
    @ucs = @user.user_profile.current_semester

    if valid_selected_course
      @@selected_courses.each do |sc|
        CourseUser.create(course_id: sc.id, user_id: @user.id, semester: @ucs+1)
      end
      @user.user_profile.current_semester += 1
      @user.user_profile.save
    end
    @@selected_courses = []
    redirect_to welcome_student_index_path
  end

  def sel_for_backlog
    @course = Course.find(params[:course_id])
    @@selected_courses_backlog.append(@course)
  end

  def reg_backlog
    @user = User.find(params[:u_id])
    @ucs = @user.user_profile.current_semester

    if @@selected_courses_backlog.count <= 3
      @@selected_courses_backlog.each do |sc|
        CourseUser.create(course_id: sc.id, user_id: @user.id, semester: -@ucs)
      end
    end
    @@selected_courses_backlog = []

    redirect_to welcome_student_course_status_path(u_id:@user.id)
  end

  def course_status
    @user = User.find(params[:u_id])
    @ucs = @user.user_profile.current_semester
    @user_curr_pass = CourseUser.where(user_id:@user.id, semester:@ucs, result:1).or(
      CourseUser.where(user_id:@user.id, semester:-@ucs, result:1)
    )
    @user_all_pass = CourseUser.where(user_id:@user.id, result:1)
    @user_all_fail = CourseUser.where(user_id:@user.id, result:2)
    @user_curr_registered_log = CourseUser.where(user_id:@user.id, semester:-@ucs, result:0)

    @user_curr_pass_info = []
    @user_curr_pass.each do |uc|
      @c = Course.find_by(id: uc.course_id)
      @user_curr_pass_info.append(code:@c.code, title:@c.title)
    end

    @user_need_reg_info = []
    @user_all_fail.each do |uc|
      @c = Course.find_by(id: uc.course_id)
      if CourseUser.find_by(course_id:@c.id, user_id:@user.id, semester:-@ucs, result:0) == nil &&
        CourseUser.find_by(course_id:@c.id, user_id:@user.id, semester:-@ucs, result:1) == nil
        @user_need_reg_info.append(c_id:@c.id, code:@c.code, title:@c.title)
      end
    end

    @user_all_pass_info = []
    if @user_all_pass.count 
      @user_all_pass.each do |uc|
        @c = Course.find_by(id: uc.course_id)
        if uc.semester < @ucs && uc.semester >0
          @user_all_pass_info.append(code:@c.code, title:@c.title)
        end
      end
    end

    @user_curr_registered_log_info = []
    @user_curr_registered_log.each do |uc|
      @c = Course.find_by(id: uc.course_id)
      @user_curr_registered_log_info.append(c_id:@c.id, code:@c.code, title:@c.title, status:"pending")
    end
  end

  private
  def valid_selected_course
    @x=1
    @p = @user.user_profile.department.courses.where(semester:@ucs+1, option:"mandatory")
    @p.each do |pc|
      if @@selected_courses.include? pc
        @x = @x + 1
      else
        @x=0
        return false
      end
    end
    @total_credit = @@selected_courses.to_a.sum{|course| course.credit}
    if @@selected_courses.count >= 1 && @@selected_courses.count <=8 && @total_credit < 40 && @x>0
      return true
    else
      return false
    end
  end
end

app/helpers/welcome_student_helper.rb
module WelcomeStudentHelper
end

app/views/welcome_student/available_courses.html.erb
<% if @user.user_profile %>
    <% dept = @user.user_profile.department %>
    <% uns = @user.user_profile.current_semester + 1 %>
    <h2>Available Courses in <%= dept.name %> to enroll now</h2>
    <p><b>Note:</b> To register for new semester you need to select at least 5 courses and at most 8 courses. Total Credit of your selected Courses must be between 30.00 and 40.00. Also, you can't register unless you select all the mandatory courses.</p>
    <table class="table table-hover table align-middle">
        <thead>
            <tr>
                <th>Code</th>
                <th>Title</th>
                <th>Credit</th>
                <th colspan="3"></th>
            </tr>
        </thead>
        <tbody>
            <% dept.courses.each do |course| %>
                <% if course.semester == uns %>
                    <tr>
                    <td><%= course.code %></td>
                    <td><%= course.title %></td>
                    <td><%= course.credit %></td>
                    <td><b><%= course.option %></b></td>
                    <td><%= link_to 'See Details', courses_show_courses_user_path(course: course), :class => "link-primary" %></td>
                    <td><%= button_to 'Select to Enroll', welcome_student_sel_to_enroll_path(course_id: course.id), :class => "btn btn-outline-primary btn-sm" %></td>
                    </tr>  
                <% end %>
            <% end %>
        </tbody>
    </table>
    <br>
    <% if @notice == "" %>
        <%= button_to 'Register for new semester', welcome_student_enroll_courses_path(u_id: @user.id), :class => "btn btn-primary btn-sm " %>
    <% else %>
        <b><%= @notice %></b>
    <% end %>
    
<% else %>
    <h6>Please set your profile first.</h6>
<% end %>

app/views/welcome_student/course_status.html.erb
<div class="row">
    <div class="col">
        <h5>Courses you have passed in this semester</h5>
        <% if @user_curr_pass_info.count == 0 %>
            <p class="card-text">Nothing to show now.</p>
        <% else %>
        <ul class="list-group">
            <% @user_curr_pass_info.each do |uc| %>
                <li class="list-group-item"><%= uc[:code] %><br><%= uc[:title] %></li>
            <% end %>
        </ul>
        <% end %> <br>
    </div>
    <div class="col">
        <h5>Courses you have passed before</h5>
        <% if @user_all_pass_info.count == 0 %>
            <p class="card-text">Nothing to show now.</p>
        <% else %>
        <ul class="list-group">
            <% @user_all_pass_info.each do |uc| %>
                <li class="list-group-item"><%= uc[:code] %><br><%= uc[:title] %></li>
            <% end %>
        </ul>
        <% end %> <br>
    </div>
    <div class="col">
        <h5>Courses you need to pass through Backlog</h5>
        <p>Note: You can select at most three courses at a time.</p>
        <% if @user_all_fail.count == 0 %>
            <p class="card-text">Nothing to show now.</p>
        <% else %>
            <% if @user_curr_registered_log_info.count > 0 %>
                <ul class="list-group">
                    <% @user_curr_registered_log_info.each do |uc| %>
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col">
                                    <%= uc[:code] %><br><%= uc[:title] %><br>
                                </div>
                                <div class="col" style="text-align:right">
                                    <b>Already registered</b><br>
                                    <b>Result: <%= uc[:status] %>
                                </div>
                            </div>
                        </li>
                    <% end %>
                </ul>
            <% end %>
            <ul class="list-group">
              <% @user_need_reg_info.each do |uc| %>
                <li class="list-group-item">
                  <div class="row">
                    <div class="col">
                    <%= uc[:code] %><br><%= uc[:title] %><br>
                    </div>
                    <div class="col" style="text-align:right">
                      <%= button_to 'Select', welcome_student_sel_for_backlog_path(course_id: uc[:c_id]), :class => 'btn btn-outline-primary btn-sm' %>
                    </div>
                  </div>
                </li>
              <% end %>
            </ul>
            <br>
            <% if @user_need_reg_info.count==0 %>
                <b>You have passed all the courses. You don't need to register for backlog.</b>
            <% else %>
                <%= button_to 'Register for Backlog', welcome_student_reg_backlog_path(u_id: @user.id), :class => 'btn btn-primary btn-sm' %>
            <% end %>
        <% end %> <br>
    </div>
</div>

app/views/welcome_student/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Home', welcome_student_index_path, :class => "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
      <% if @check==3 %>
        <li><%= link_to 'Courses', course_dept_show_courses_user_path(dept_id: @user.user_profile.department_id ), :class => "nav-link" %></li>
        <li><%= link_to 'Chatrooms', chatrooms_url, :class => "nav-link" %></li>
      <% elsif @check==2 %>
        <li><%= link_to 'Courses', course_dept_show_courses_user_path(dept_id: "-2" ), :class => "nav-link" %></li>
      <% else %>
        <li><%= link_to 'Courses', course_dept_show_courses_user_path(dept_id: "-1" ), :class => "nav-link" %></li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>
<br>
<div class="container-fluid">
    <div class="row">
        <div class="col-4">
          <ul class="list-group">
            <% if @check==3 %>
              <li class="list-group-item"><%= image_tag @user.user_profile.profile_picture, :style =>'width:60%' %></li>
            <% end %>  
            <li class="list-group-item">Name: <%= @user_name %> </li>
            <li class="list-group-item">Email: <%= @user_email %> </li>
            <% if @check==3 %>  
              <% dept = Department.find_by(id: @user.user_profile.department_id) %>
              <% dept_name = dept.name %>
              <li class="list-group-item">Department: <%= dept_name %> </li>
              <li class="list-group-item">Current Semester: <%= @user.user_profile.current_semester %> </li>
              <li class="list-group-item">Address: <%= @user.user_profile.address %> </li>
              <li class="list-group-item">Blood Group: <%= @user.user_profile.blood_group %> </li>
            <% end %>
          </ul>
          <% if @check==3 %>
            <br>
            <%= link_to "Want to update Information?", edit_user_profile_path(@user.user_profile, u_id: @user_id), :class => "link-primary" %>
            <br>
          <% elsif @check==2 %> 
            <br>
            <% if @user.user_profile.checked==false && @user.reject_profile_messages[0] == nil %>
              <b>You've set your profile. Please wait for admin approval.</b>
            <% elsif @user.reject_profile_messages[0] != nil %>
              <b>Admin has rejected your previous profile.</b><br>
              <b>Message: </b>
              <p><%= @user.reject_profile_messages[0].body %></p>
              <br>
              <%= link_to "Set your profile again", new_user_profile_path, :class => "link-primary" %>
              <br>
            <% end %>
            <br><br>
          <% else %>
            <br>
            <%= link_to "Want to set your profile?", new_user_profile_path, :class => "link-primary" %>
            <br>
          <% end %>
          <br>
          <%= button_to 'Logout', destroy_user_session_path, method: :delete, :class => "btn btn-danger" %>
        </div>

        <div class="col-8">
          <div class="row">
            <div class="col-6">
              <div class="card" style="width: 100%;">
                <div class="card-body">
                  <% if @check==3 %>
                    <h5 class="card-title">You have enrolled <%= @user_curr_courses.count %> courses for the current semester.</h5>
                    <% if @user_curr_courses.count == 0 %>
                      <p class="card-text">Nothing to show now.</p>
                    <% end %>
                    <ul class="list-group">
                      <% @user_curr_courses_info.each do |uc| %>
                        <li class="list-group-item"><%= uc[:code] %><br><%= uc[:title] %>
                        <br><b>Result: <%= uc[:status] %></b></li>
                      <% end %>
                    </ul>
                    <br>
                    <%= button_to 'Enroll for new semester', welcome_student_available_courses_path(u_id: @user_id), :class => 'btn btn-primary btn-sm' %>
                  <% elsif @check == 2 %>
                    <h5 class="card-title">You haven't enrolled yet.</h5>
                    <p class="card-text">Please wait for admin approval first.</p>
                  <% else %>
                    <h5 class="card-title">You haven't set your profile yet.</h5>
                    <p class="card-text">Complete your profile setup first to be able to enroll.</p>
                  <% end %> <br>
                </div>
              </div>
            </div>
            <div class="col-6">
              <div class="card" style="width: 100%;">
                <div class="card-body">
                    <% if @check==3 %>
                      <h5 class="card-title">You have passed <%= @user_passed_courses.count %> courses.</h5>
                      <p class="card-text">You need to pass <%= dept.courses.count - @user_passed_courses.count %> courses more.</p>
                      <%= button_to 'See Details', welcome_student_course_status_path(u_id: @user), :class => "btn btn-primary btn-sm" %>
                    <% elsif @check==2 %>
                      <p class="card-text">Please wait for admin approval.</p>
                    <% else %>
                      <p class="card-text">Complete your profile setup first and enroll courses to pass.</p>
                    <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>