config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :users do
    resources :reject_profile_messages
  end

  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
  resources :user_profiles
  post 'welcome_student/reg_backlog'
  post 'welcome_student/sel_for_backlog'
  post 'users/approve_user'
  post 'users/set_fail_log'
  post 'users/set_pass_log'
  post 'users/set_fail'
  post 'users/set_pass'
  get 'welcome_student/course_status'
  post 'welcome_student/course_status'
  get 'courses/show_courses_user'
  get 'courses/show_user'
  post 'welcome_student/enroll_courses'
  post 'welcome_student/sel_to_enroll'
  post 'welcome_student/available_courses'
  get 'welcome_student/available_courses'
  get 'departments/show_user'
  get 'course_dept/show_courses_user'
  get 'welcome_student/index'
  post 'course_dept/remove_course'
  post 'course_dept/add_course'
  post 'course_dept/sel_course'
  get 'course_dept/show_courses'
  get 'course_dept/index'
  get 'welcome/index'

  get 'first/index'
  root 'first#index'
  resources :admins
  resources :departments
  resources :courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount ActionCable.server => '/cable'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
    has_many    :chatroom_users
    has_many    :users, through: :chatroom_users
    has_many    :messages 
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/course.rb
class Course < ApplicationRecord
    validates   :code, :title, :credit, :days, presence: true
    validates   :code, :title, uniqueness:true
    validates   :credit, numericality: { greater_than_or_equal_to: 0.01 }
    has_and_belongs_to_many :departments

    has_many  :course_users
    has_many  :users, through:  :course_users
end

app/models/course_user.rb
class CourseUser < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/department.rb
class Department < ApplicationRecord
    validates   :name, presence:true, uniqueness:true
    has_many    :user_profiles
    has_and_belongs_to_many :courses
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one   :user_profile

  has_many  :course_users
  has_many  :courses, through:  :course_users

  has_many  :chatroom_users
  has_many  :chatrooms, through: :chatroom_users
  has_many  :messages

  has_many   :reject_profile_messages
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :department
  belongs_to :user

  has_one_attached  :profile_picture
  #validates :correct_image_type


  private
  def correct_image_type
    if profile_picture.attached? && !profile_picture.content_type.in?(%w(profile_picture/jpeg))
      errors.add(:profile_picture, 'must be a type of jpeg or png.')
    elsif profile_picture.attached? == false
      errors.add(:profile_picture, 'must have an image.')
    end
  end
end

app/controllers/course_dept_controller.rb
class CourseDeptController < ApplicationController
  skip_before_action :authenticate_admin!, only: [:show_courses_user]
  skip_before_action :authenticate_user! , only: [:index, :show_courses, :sel_course, :add_course, :remove_course]
  
  @@selected_courses = []

  def index
    @dept = Department.find(params[:dept_id])
    @courses = Course.all
  end
  
  def show_courses
    @dept = Department.find(params[:dept_id])
    respond_to do |format|
      format.html{redirect_to welcome_index_path}
      format.js
    end
  end

  def show_courses_user
    if params[:dept_id] == "-2"
      @ch = 2
    elsif params[:dept_id] == "-1"
      @ch = 1
    else
      @dept = Department.find(params[:dept_id])
    end
  end

  def sel_course
    @course = Course.find(params[:course_id])
    puts @course
    @@selected_courses.append(@course)
  end

  def add_course
    puts "I am here"
    @dept = Department.find(params[:dept_id])
    @dept.courses.push(@@selected_courses)
    @@selected_courses = []
    redirect_to welcome_index_path
  end

  def remove_course
    @dept = Department.find(params[:dept_id])
    @dept.courses.delete(@@selected_courses)
    @@selected_courses = []
    redirect_to welcome_index_path
  end
end

app/controllers/first_controller.rb
class FirstController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :authenticate_admin!
  def index
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/course_dept_helper.rb
module CourseDeptHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/first_helper.rb
module FirstHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/course_dept/_course_dept.html.erb
<h1>Manage courses for <%= dept.name %> </h1>

<table class="table table-hover table align-middle">
  <thead>
    <tr>
      <th>Code</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% courses.each do |course| %>
        <tr>
        <td><%= course.code %></td>
        <td><%= link_to 'See Details', course, :class => "link-primary" %></td>
        <td>
        <% if dept.courses.include?(course) %>
          <%= button_to 'Select to Remove', course_dept_sel_course_path(course_id: course), :class => "btn btn-outline-primary btn-sm" %>
        <% else %>
          <%= button_to 'Select to Add', course_dept_sel_course_path(course_id: course), :class => "btn btn-outline-primary btn-sm" %>
        <% end %>
        </td>
        </tr>       
    <% end %>
  </tbody>
</table>
<%= button_to 'Add Courses', course_dept_add_course_path(dept_id: dept), :class => "btn btn-primary btn-sm " %><br>
<%= button_to 'Remove Courses', course_dept_remove_course_path(dept_id: dept), :class => "btn btn-primary btn-sm" %>

app/views/course_dept/_show_courses.html.erb
<h6>All courses for <%= department.name %> </h1>

<table class="table table-hover table align-middle">
  <thead>
    <tr>
      <th>Code</th>
      <th>Title</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% department.courses.each do |course| %>
        <tr>
        <td><%= course.code %></td>
        <td><%= course.title %></td>
        <td><%= link_to 'See Details', course, :class => "link-primary" %></td>
        </tr>       
    <% end %>
  </tbody>
</table>

app/views/course_dept/index.html.erb
<%= render "course_dept", dept:@dept, courses:@courses %>
<br>
<%= link_to 'Cancel', welcome_index_path, :class => "link-danger" %>

app/views/course_dept/show_courses.js.erb
x = document.getElementById("demo")
x.innerHTML = "<%= j render 'course_dept/show_courses', department:@dept %>"

app/views/course_dept/show_courses_user.html.erb
<% if @ch == 1 %>
  <h6> You haven't set your profile yet. </h6>
<% elsif @ch == 2 %>
  <h6> Sorry, your profile hasn't been approved yet. </h6>
<% else %>
<h1>All courses for <%= @dept.name %> </h1>

<table class="table table-hover table align-middle">
  <thead>
    <tr>
      <th>Code</th>
      <th>Title</th>
      <th>Credit</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @dept.courses.each do |course| %>
        <tr>
        <td><%= course.code %></td>
        <td><%= course.title %></td>
        <td><%= course.credit %></td>
        <td><b><%= course.option %></b></td>
        <td><%= link_to 'See Details', courses_show_courses_user_path(course: course), :class => "link-primary" %></td>
        </tr>       
    <% end %>
  </tbody>
</table>
<% end %>