config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :users do
    resources :reject_profile_messages
  end

  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
  resources :user_profiles
  post 'welcome_student/reg_backlog'
  post 'welcome_student/sel_for_backlog'
  post 'users/approve_user'
  post 'users/set_fail_log'
  post 'users/set_pass_log'
  post 'users/set_fail'
  post 'users/set_pass'
  get 'welcome_student/course_status'
  post 'welcome_student/course_status'
  get 'courses/show_courses_user'
  get 'courses/show_user'
  post 'welcome_student/enroll_courses'
  post 'welcome_student/sel_to_enroll'
  post 'welcome_student/available_courses'
  get 'welcome_student/available_courses'
  get 'departments/show_user'
  get 'course_dept/show_courses_user'
  get 'welcome_student/index'
  post 'course_dept/remove_course'
  post 'course_dept/add_course'
  post 'course_dept/sel_course'
  get 'course_dept/show_courses'
  get 'course_dept/index'
  get 'welcome/index'

  get 'first/index'
  root 'first#index'
  resources :admins
  resources :departments
  resources :courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount ActionCable.server => '/cable'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
    has_many    :chatroom_users
    has_many    :users, through: :chatroom_users
    has_many    :messages 
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/course.rb
class Course < ApplicationRecord
    validates   :code, :title, :credit, :days, presence: true
    validates   :code, :title, uniqueness:true
    validates   :credit, numericality: { greater_than_or_equal_to: 0.01 }
    has_and_belongs_to_many :departments

    has_many  :course_users
    has_many  :users, through:  :course_users
end

app/models/course_user.rb
class CourseUser < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/department.rb
class Department < ApplicationRecord
    validates   :name, presence:true, uniqueness:true
    has_many    :user_profiles
    has_and_belongs_to_many :courses
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one   :user_profile

  has_many  :course_users
  has_many  :courses, through:  :course_users

  has_many  :chatroom_users
  has_many  :chatrooms, through: :chatroom_users
  has_many  :messages

  has_many   :reject_profile_messages
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :department
  belongs_to :user

  has_one_attached  :profile_picture
  #validates :correct_image_type


  private
  def correct_image_type
    if profile_picture.attached? && !profile_picture.content_type.in?(%w(profile_picture/jpeg))
      errors.add(:profile_picture, 'must be a type of jpeg or png.')
    elsif profile_picture.attached? == false
      errors.add(:profile_picture, 'must have an image.')
    end
  end
end

app/controllers/first_controller.rb
class FirstController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :authenticate_admin!
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action  :authenticate_user!
  def index
    if admin_signed_in?
      cadmin = current_admin
      @admin_name = cadmin.name
      @admin_email = cadmin.email

      @depts = Department.all
    end
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/course_dept_helper.rb
module CourseDeptHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/first_helper.rb
module FirstHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Home', welcome_index_path, :class => "navbar-brand" %></li>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <%= link_to 'Courses', courses_path, :class => "nav-link" %></li>
        <%= link_to 'Departments', departments_path, :class => "nav-link" %></li>
        <%= link_to 'Users', users_path, :class => "nav-link" %></li>
      </ul>
    </div>
  </div>
</nav>
<br>
<div class="container-fluid">
  <div class="row">
    <div class="col-3">
      <% if admin_signed_in? %>
        <ul class="list-group">
            <li class="list-group-item">Name: <%= @admin_name %> </li>
            <li class="list-group-item">Email: <%= @admin_email %> </li>
        </ul>
        <br>
        <%= button_to 'Logout', destroy_admin_session_path, method: :delete, :class => "btn btn-danger" %>
      <% end %>
    </div>
    <div class="col-4">
      <h4>Current Departements</h4>
      <table class="table table-hover">
        <thead>
            <tr>
            <th>Name</th>
            <th>Total Courses</th>
            <th colspan="2"></th>
            </tr>
        </thead>
    
        <tbody>
            <% @depts.each do |department| %>
            <tr>
                <td><%= department.name %></td>
                <td><%= department.courses.count %></td>
                <td>
                  <%= link_to "Manage Courses", course_dept_index_path(dept_id: department) %>
                </td>
                <td>
                  <%= link_to "See Courses", course_dept_show_courses_path(dept_id: department), remote: true %>
                </td>
            </tr>
            <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-5">
      <h4>Courses under your selected department</h4>
      <div id="demo">
        <p>You didn't select any department.</p>
      </div>
    </div>
  </div>
</div>