config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :users do
    resources :reject_profile_messages
  end

  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
  resources :user_profiles
  post 'welcome_student/reg_backlog'
  post 'welcome_student/sel_for_backlog'
  post 'users/approve_user'
  post 'users/set_fail_log'
  post 'users/set_pass_log'
  post 'users/set_fail'
  post 'users/set_pass'
  get 'welcome_student/course_status'
  post 'welcome_student/course_status'
  get 'courses/show_courses_user'
  get 'courses/show_user'
  post 'welcome_student/enroll_courses'
  post 'welcome_student/sel_to_enroll'
  post 'welcome_student/available_courses'
  get 'welcome_student/available_courses'
  get 'departments/show_user'
  get 'course_dept/show_courses_user'
  get 'welcome_student/index'
  post 'course_dept/remove_course'
  post 'course_dept/add_course'
  post 'course_dept/sel_course'
  get 'course_dept/show_courses'
  get 'course_dept/index'
  get 'welcome/index'

  get 'first/index'
  root 'first#index'
  resources :admins
  resources :departments
  resources :courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount ActionCable.server => '/cable'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
    has_many    :chatroom_users
    has_many    :users, through: :chatroom_users
    has_many    :messages 
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/course.rb
class Course < ApplicationRecord
    validates   :code, :title, :credit, :days, presence: true
    validates   :code, :title, uniqueness:true
    validates   :credit, numericality: { greater_than_or_equal_to: 0.01 }
    has_and_belongs_to_many :departments

    has_many  :course_users
    has_many  :users, through:  :course_users
end

app/models/course_user.rb
class CourseUser < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/department.rb
class Department < ApplicationRecord
    validates   :name, presence:true, uniqueness:true
    has_many    :user_profiles
    has_and_belongs_to_many :courses
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one   :user_profile

  has_many  :course_users
  has_many  :courses, through:  :course_users

  has_many  :chatroom_users
  has_many  :chatrooms, through: :chatroom_users
  has_many  :messages

  has_many   :reject_profile_messages
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :department
  belongs_to :user

  has_one_attached  :profile_picture
  #validates :correct_image_type


  private
  def correct_image_type
    if profile_picture.attached? && !profile_picture.content_type.in?(%w(profile_picture/jpeg))
      errors.add(:profile_picture, 'must be a type of jpeg or png.')
    elsif profile_picture.attached? == false
      errors.add(:profile_picture, 'must have an image.')
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :authenticate_admin!, only: [:show_courses_user]
  before_action :set_course, only: %i[ show edit update destroy ]
  # skip_before_action  :authorize, only: %i[ show_courses_user]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  def show_user 
    @course = Course.find(params[:course])
  end

  def show_courses_user
    puts "I am in show courses user"
    puts params[:course]
    @course = Course.find(params[:course])
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:code, :title, :description, :prerequisite, :credit, :days, :semester, :option)
    end
end

app/controllers/first_controller.rb
class FirstController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :authenticate_admin!
  def index
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/course_dept_helper.rb
module CourseDeptHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/first_helper.rb
module FirstHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :prerequisite %>
    <%= form.text_field :prerequisite %>
  </div>

  <div class="field">
    <%= form.label :credit %>
    <%= form.text_field :credit %>
  </div>

  <div class="field">
    <%= form.label :semester %>
    <%= form.number_field :semester %>
  </div>

  <div class="field">
    <%= form.label :option %>
    <%= form.text_field :option %>
  </div>

  <div class="field">
    <%= form.label :days %>
    <%= form.number_field :days %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Courses</h1>

<table class="table table-hover table align-middle">
  <thead>
    <tr>
      <th>Code</th>
      <th>Title</th>
      <th>Description</th>
      <th>Prerequisite</th>
      <th>Credit</th>
      <th>Days</th>
      <th>Semester</th>
      <th>Enrolled Students</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.code %></td>
        <td><%= course.title %></td>
        <td><p>
        <%= truncate(strip_tags(course.description),
        length: 50) %>
        </p></td>
        <td><%= course.prerequisite %></td>
        <td><%= course.credit %></td>
        <td><%= course.days %></td>
        <td><%= course.semester %></td>
        <td><%= link_to course.users.count, courses_show_user_path(course: course) %></td>
        <td>
          <ul>
            <li><%= link_to 'Show', course, :class => "link-primary" %></li>
            <li><%= link_to 'Edit', edit_course_path(course), :class => "link-success" %></li>
            <li><%= link_to 'Destroy', course, method: :delete, :class => "link-danger", data: { confirm: 'Are you sure?' } %></li>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New Course', new_course_path, method: :get, :class => "btn btn-primary" %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p>
  <strong>Code:</strong>
  <%= @course.code %>
</p>

<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>

<p>
  <strong>Prerequisite:</strong>
  <%= @course.prerequisite %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @course.credit %>
</p>

<p>
  <strong>Days:</strong>
  <%= @course.days %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @course.semester %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/courses/show_courses_user.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @course.code %>
</p>

<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>

<p>
  <strong>Prerequisite:</strong>
  <%= @course.prerequisite %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @course.credit %>
</p>

<p>
  <strong>Days:</strong>
  <%= @course.days %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @course.semester %>
</p>

<!-- <%= link_to 'Edit', edit_course_path(@course) %> | 
<%= link_to 'Back', courses_path %> -->

app/views/courses/show_user.html.erb
<h1>Students in this course</h1>


<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% if @course.users %>
        <% @course.users.each do |cu| %>
            <tr>
                <td><%= cu.name %></td>
                <td><%= cu.email %></td>
                <td><%= link_to 'See Details', cu %></td>
            </tr>
        <% end %>
    <% else %>
        <tr>
            <td>No student</td>
        </tr>
    <% end %>
  </tbody>
</table>
<br>